### ISSUE TITLE
Twitter geo-tagger

### ISSUE THREAD

**Issue by Yicong-Huang** [ISG-ICS/TwiCrawler#4]
Infer a tweet's location based on the following levels:

1. Exact lat, lng.
2. Tweet location (city, county, or state level). 
3. User profile location (city, county, or state level). 
4. Tweet content location (landmark, city, county, or state level). 

Provide an estimation lat log for the the 2nd ~ 4th levels.

Takes a tweet json as input and output a tagged json.

**Comment by ChankiWu** [comment]
There are several fields in the Tweet JSON which are related to the geoinformation we want. 
1. `place` contains the city_name and four coordinates.
2. `coordinates` contains (longitude first, then latitude)
3. `user` contains a field called `location` such as "San Francisco, CA".

If there are more useful fields, please feel free to add.

Some consideration:
If we want to get the city, county, state information based on the above, what the priorities we consider? And if we use city.json to find the county and state info, how to get them efficiently when we want to tag a tweet? Besides, if there are two cities in the different county or state but has the same city_name, we couldn't decide its county and state only based on the city name I think? Maybe we could refer to some geo info API? 

[Tweet JSON Link](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object)

**Comment by Yicong-Huang** [comment]
It will be better if you list questions with numbers. 

1. As requirement for @baiqiushi, should use the 1) first, then 2), then bounding box, then 3). 
2. city.json and all other jsons are small enough to be loaded in memory as flattened hash maps. 
3. If there is conflict (share same city name), use logic to find which state/county it belongs to. Of course we need to look for more information to resolve the conflict.
4. some geo Info API is possible to be utilized, if matching two conditions: 
    - it's free.
    - it can support the massive volume of the incoming tweets.
    With the two limitations, such API might not be a good solution.

**Comment by baiqiushi** [comment]
For the priority order we infer the location from should be: 
1. Location text (Twitter explicitly saying this tweet comes from which city name); 
2. Coordinate (Twitter explicitly saying this tweet comes from which GPS location); 
3. Bounding_box (Twitter explicitly saying this tweet comes from which GPS small square, this square is usually much smaller than a city’s polygon), how to do the search using a square against polygons? Please refer to the java code of current script; 
4. User location; (not accurate, but as long as we take down we infer the location using this information, we are fine. The applications can decide whether they want to use this information or not); 
5. Text inside tweet; (even less accurate, but still as long as we know it, we are good.) 
6. If none of the above can be found in a tweet, give it a default value; (e.g. `None`)

**Comment by ChankiWu** [comment]
I am currently working on the coordinates in the Tweet. As we talked before, if there is no `place` field in the tweet, we would use `coordinates` or `bounding_box` to get the (Long, Lat). And we infer the city, county, state information based on this (Long, Lat).

I have some problems and concerns about this:

1. I tried to load each city's polygon information from the `city.json`. And then we judge if the (Long, Lat) is in the polygon. This process is very time-consuming. First, a city's polygon could be one polygon or MultiPolygon and most in a weird shape. To traverse the polygon data and build a "hashmap" is very time-consuming, and I wait for more than 40 seconds I think so I killed the loading process. Second, actually the polygon couldn't be hashed, so in my understanding, maybe we need to traverse all the polygons each time to match a city's coordinate. That is not what we want I think because this is just an estimation which should be efficient and simple.

2. My solution is to use [GEOPY](https://geopy.readthedocs.io/en/stable/) which could return your address based on your (Lat, Long) and could be easily installed with pip. This way is more simple and accurate I believe and I recommend this way.

However, no matter what you do, there will always be a deviation because the coordinates we get from Twitter is being encrypted or processed I guess. For example, the coordinate of Washington, DC I get from the Twitter's example website is not the exact one. I also used that in the GEOPY and I get Philadelphia which is neighbor.

Feel free to give some opinions or ideas, thanks a lot.

**Comment by Yicong-Huang** [comment]
I talked to @baiqiushi and we did not look into details of `GEOPY`. We think it's fine as long as the library is free and the location inferred is accurate. Can you do a small experiment to check the result before applying it?

In this case, there is no need to use the polygon defined in json. You can reduce the amount of hash map load into memory as well.

**Comment by ChankiWu** [comment]
> I talked to @baiqiushi and we did not look into details of `GEOPY`. We think it's fine as long as the library is free and the location inferred is accurate. Can you do a small experiment to check the result before applying it?
> 
> In this case, there is no need to use the polygon defined in json. You can reduce the amount of hash map load into memory as well.

Thank you so much. Actually, the `GEOPY` is very accurate and it is generally accepted that this official API should be more efficient and accurate than calculating the polygon on my own haha. In fact, I have done the experiment and just as I stated in my previous comment, the coordinates we get from Twitter may being encrypted or processed. For example, the coordinate of Washington, DC I get from Twitter's website example is not the exact and real one. I also used that in the `GEOPY` and I get Philadelphia which is a neighbor of Washington, DC. Of course, I checked the Washington, DC's accurate (Long, Lat) and it is not the one given in Twitter's example website. And I think that is the deviation we could accept.

**Comment by ChankiWu** [comment]
> For the priority order we infer the location from should be:
> 
> 1. Location text (Twitter explicitly saying this tweet comes from which city name);
> 2. Coordinate (Twitter explicitly saying this tweet comes from which GPS location);
> 3. Bounding_box (Twitter explicitly saying this tweet comes from which GPS small square, this square is usually much smaller than a city’s polygon), how to do the search using a square against polygons? Please refer to the java code of current script;
> 4. User location; (not accurate, but as long as we take down we infer the location using this information, we are fine. The applications can decide whether they want to use this information or not);
> 5. Text inside tweet; (even less accurate, but still as long as we know it, we are good.)
> 6. If none of the above can be found in a tweet, give it a default value; (e.g. `None`)

For now, I have basically finished the logic of 1-4 steps. And just like we talked on Monday, for step 5 we may use NLP to extract the location information, and text content in Tweet may not have good results or help to this tweet's location information. I think it is not worth it. In my opinion, I suggest we infer the location until step 4, and if it is empty, we could give it a None. What do your guys think?

**Comment by Yicong-Huang** [comment]
We can leave it into two phases. For now up to step 4 sounds good enough, but please leave the API open to easy addition of logic for step 5.

You can request review for geo-tagger PR if you think it is ready and I can check tonight.

**Comment by ChankiWu** [comment]
> We can leave it into two phases. For now up to step 4 sounds good enough, but please leave the API open to easy addition of logic for step 5.
> 
> You can request review for geo-tagger PR if you think it is ready and I can check tonight.

Thanks, sounds good. I will try to give a PR for you to review tonight.
